### PR TITLE
Added available link to Grab + New Speech model from Facebook

### PR DESCRIPTION
**Pull request by Bharat123rox**

### CODE REVIEW

**Comment by eugeneyan** [comment]
Thanks for sharing this! I see that the links to the Facebook resources contain the `fbclid` param—do you mind cleaning it up please?

**Comment by Bharat123rox** [comment]
@eugeneyan Cleaned it up now!

**Comment by eugeneyan** [comment]
Thanks for sharing this!

**Comment by Bharat123rox** [comment]
Even I love staying updated @eugeneyan, can we have a ML system design discussion sometime?

**Comment by eugeneyan** [comment]
Sure, perhaps you could email me at eugene@eugeneyan.com?

**Pull request merged**
