### PR TITLE
Add QuintoAndar Butterfree

### PR DESCRIPTION
**Pull request by AlvaroMarquesAndrade**
Hi, I've added a new reference within the Feature Store section. It's [Butterfree](https://medium.com/quintoandar-tech-blog/butterfree-a-spark-based-framework-for-feature-store-building-48c3640522c7), an [open-source](https://github.com/quintoandar/butterfree) Spark-based framework for Feature Store building. Thanks!

### CODE REVIEW

**Comment by awcchungster** [comment]
I've met some of their team to understand the system and endorse.

**Comment by eugeneyan** [comment]
Thanks for sharing this @AlvaroMarquesAndrade! In this repo, we try share examples and case studies from organizations, so others can learn from their experiences. **Do you have a case study of an organization using Butterfree?**

Alternatively, you can try submitting a PR to [featurestore.org](https://www.featurestore.org).

**Comment by allrod5** [comment]
@eugeneyan the article @AlvaroMarquesAndrade shared is both an introduction to the framework and an example of its use at the QuintoAndar organization. Very similar to the first article in this very same section about Feast.

**Comment by AlvaroMarquesAndrade** [comment]
As stated by @allrod5, Butterfree is a case study of [QuintoAndar](https://www.crunchbase.com/organization/quintoandar), a real state company in Brazil. Sorry about not making this clear within my PR description, @eugeneyan. 

Thanks for the suggestion regarding [featurestore.org](https://www.featurestore.org/) and please let me know if further information is required.

**Comment by eugeneyan** [comment]
Thanks for clarifying everyone. Upon closer reading, I see that it's based on QuintoAndar's use case—apologies for missing it earlier.

**Pull request merged**
