### PR TITLE
hopsworks feature store

### PR DESCRIPTION
**Pull request by jimdowling**

### CODE REVIEW

**Comment by eugeneyan** [comment]
Hi Jim,

Thanks for contributing! 

Do you have a use case to share, where a team has adopted the Hopworks Feature Store in their data or machine learning-related work? Ideally, we want to show how these various tools and techniques are applied so readers can follow along.

**Comment by jimdowling** [comment]
There's customer references on our website. Here's a couple:
https://www.logicalclocks.com/finance
(there is a spark summit talk by Swedbank on using Fraud detection with Hopsworks)
and the world's largest betting company PaddyPower
https://www.logicalclocks.com/betting

**Comment by eugeneyan** [comment]
Thanks Jim. I'm afraid those references don't provide enough detail on how other teams can replicate the work. 

Nonetheless, I found the Swedbank [video](https://databricks.com/session_eu19/deep-anomaly-detection-from-research-to-production-leveraging-spark-and-tensorflow) and will add it under anomaly detection, together with the Hopsworks [video](https://www.youtube.com/watch?v=TgXVU8DSyCQ&feature=youtu.be).

**Comment by eugeneyan** [comment]
Added in this PR [here](https://github.com/eugeneyan/applied-ml/commit/06f2ea1346c5f15a943a65761bd1c07a746688d3). Will close this PR.

**Pull request closed without merging**
