### PR TITLE
Added facebook prophet to forecasting block

### PR DESCRIPTION
**Pull request by nilesh-patil**
Added links for facebook prophet ( one of the most common tool to come up recently for forecasting at scale):

1. Link for Prophet Homepage
2. Link for Prophet paper

@eugeneyan

### CODE REVIEW

**Comment by eugeneyan** [comment]
Hey Nilesh, 

Thanks for this PR. I'm not seeing examples of how Facebook used it to solve a forecasting problem though. Could you point me to it please? We try to include papers that help answer the following questions below.

Figuring out how to implement your ML project? Learn how other organizations did it:
- How the problem is framed 🔎(e.g., personalization as recsys vs. search vs. sequences)
- What machine learning techniques worked ✅ (and sometimes, what didn't ❌)
- Why it works, the science behind it with research, literature, and references 📂
- What real-world results were achieved (so you can better assess ROI ⏰💰📈)

**Comment by nilesh-patil** [comment]
Aah, okay. From that perspective, `fbprophet` is more like Gojek's automated forecasting tool mentioned in 4th point.

This is an extremely popular open-source tool developed for sequence prediction problems at scale within facebook which attempts to bypass the expertise required for time series forecasting => effectively scaling up the prediction process.

1. The approach taken for generating each forecast is discussed in more detail in their [Paper](https://peerj.com/preprints/3190.pdf)  and [video](https://youtu.be/pOYAXv15r3A) (the video is better at explanation :) )

2. A much more detailed industrial application is presented in this video by Databricks with spark recently : [Automatic Forecasting using Prophet, Databricks, Delta Lake and MLflow](https://www.youtube.com/watch?v=TkcpjnLh690)

There a few papers with other applications using this library, but it felt like the library ( homepage/docs & video maybe? ) make more sense rather than one off papers for this one. let me know what you think @eugeneyan

**Comment by eugeneyan** [comment]
I think the Databricks video is a great example of how `Prophet` is applied in production. How about having the Databricks video and title as the main link, and the paper in parentheses? Perhaps something like this:

-  [Automatic Forecasting using Prophet, Databricks, Delta Lake and MLflow](https://www.youtube.com/watch?v=TkcpjnLh690) ([Paper](https://peerj.com/preprints/3190.pdf), [Code](https://github.com/facebook/prophet))

**Comment by nilesh-patil** [comment]
That's a good idea. 
I've updated the doc now to show `databricks` video & then paper/code for `fbprohet`

**Comment by eugeneyan** [comment]
Thank you for your contribution! Merged!

**Pull request merged**
